name: Build and Test
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [""]
        # cover 32-bit, 64-bit, little-endian, and big-endian
        target:
          - x86_64-unknown-linux-gnu
          - thumbv6m-none-eabi
          - powerpc-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: cargo build --no-default-features --features "${{ matrix.features }}" --target "${{ matrix.target }}"
      - run: cargo test --no-default-features --features "${{ matrix.features }}" --target="${{ matrix.target }}"
